namespace Ceph.Cli.Services;

/// <summary>
/// Generates docker-compose files and supporting configuration to run a Ceph
/// cluster inside Docker on Windows (via WSL2 / Docker Desktop).
/// </summary>
public class DockerComposeGenerator
{
    public record GenerateOptions(
        string OutputDirectory,
        int MonitorCount = 1,
        int OsdCount = 3,
        int MgrCount = 1,
        string CephImage = "quay.io/ceph/ceph:v17",
        string ClusterNetwork = "172.20.0.0/16",
        bool IncludeRgw = false,
        bool IncludeMds = false
    );

    /// <summary>Generates all files into <paramref name="options"/>.OutputDirectory.</summary>
    public IReadOnlyList<string> Generate(GenerateOptions options)
    {
        Directory.CreateDirectory(options.OutputDirectory);
        var files = new List<string>();

        files.Add(WriteDockerCompose(options));
        files.Add(WriteCephConf(options));
        files.Add(WriteEntrypointScript(options));
        files.Add(WriteEnvFile(options));
        files.Add(WriteReadme(options));
        files.Add(WriteWslConfig(options));

        return files;
    }

    /// <summary>
    /// Writes text with Unix LF line endings. Files mounted into Linux containers
    /// will break if they contain Windows CRLF line endings.
    /// </summary>
    private static void WriteUnixText(string path, string content)
    {
        content = content.Replace("\r\n", "\n");
        File.WriteAllBytes(path, System.Text.Encoding.UTF8.GetBytes(content));
    }

    // -------------------------------------------------------------------------
    // docker-compose.yml
    // -------------------------------------------------------------------------

    private string WriteDockerCompose(GenerateOptions options)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Generated by ceph-cli – do not edit manually unless you know what you are doing.");
        sb.AppendLine("# Run with: docker compose up -d");
        sb.AppendLine();
        sb.AppendLine("services:");

        // MON services
        for (int i = 0; i < options.MonitorCount; i++)
        {
            string name = $"ceph-mon{i + 1}";
            string ip = $"172.20.1.{i + 1}";
            sb.AppendLine($"  {name}:");
            sb.AppendLine($"    image: {options.CephImage}");
            sb.AppendLine($"    container_name: {name}");
            sb.AppendLine($"    hostname: {name}");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    entrypoint: /entrypoint.sh");
            sb.AppendLine("    env_file: .env");
            sb.AppendLine("    environment:");
            sb.AppendLine($"      - MON_IP={ip}");
            sb.AppendLine("      - CEPH_DAEMON=MON");
            sb.AppendLine($"      - CEPH_PUBLIC_NETWORK={options.ClusterNetwork}");
            sb.AppendLine("    volumes:");
            sb.AppendLine($"      - {name}-data:/var/lib/ceph");
            sb.AppendLine("      - ceph-etc:/etc/ceph");
            sb.AppendLine("      - ./ceph.conf:/ceph.conf.seed:ro");
            sb.AppendLine("      - ./entrypoint.sh:/entrypoint.sh:ro");
            sb.AppendLine("    networks:");
            sb.AppendLine("      ceph-net:");
            sb.AppendLine($"        ipv4_address: {ip}");
            sb.AppendLine("    healthcheck:");
            sb.AppendLine("      test: [\"CMD\", \"ceph\", \"--connect-timeout\", \"5\", \"health\"]");
            sb.AppendLine("      interval: 30s");
            sb.AppendLine("      timeout: 10s");
            sb.AppendLine("      retries: 5");
            sb.AppendLine("      start_period: 60s");
            sb.AppendLine();
        }

        // MGR services
        for (int i = 0; i < options.MgrCount; i++)
        {
            string name = $"ceph-mgr{i + 1}";
            string ip = $"172.20.2.{i + 1}";
            sb.AppendLine($"  {name}:");
            sb.AppendLine($"    image: {options.CephImage}");
            sb.AppendLine($"    container_name: {name}");
            sb.AppendLine($"    hostname: {name}");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    entrypoint: /entrypoint.sh");
            sb.AppendLine("    env_file: .env");
            sb.AppendLine("    environment:");
            sb.AppendLine("      - CEPH_DAEMON=MGR");
            sb.AppendLine($"      - CEPH_PUBLIC_NETWORK={options.ClusterNetwork}");
            sb.AppendLine("    volumes:");
            sb.AppendLine($"      - {name}-data:/var/lib/ceph");
            sb.AppendLine("      - ceph-etc:/etc/ceph");
            sb.AppendLine("      - ./entrypoint.sh:/entrypoint.sh:ro");
            sb.AppendLine("    depends_on:");
            sb.AppendLine("      ceph-mon1:");
            sb.AppendLine("        condition: service_healthy");
            sb.AppendLine("    networks:");
            sb.AppendLine("      ceph-net:");
            sb.AppendLine($"        ipv4_address: {ip}");
            sb.AppendLine();
        }

        // OSD services
        for (int i = 0; i < options.OsdCount; i++)
        {
            string name = $"ceph-osd{i + 1}";
            string ip = $"172.20.3.{i + 1}";
            sb.AppendLine($"  {name}:");
            sb.AppendLine($"    image: {options.CephImage}");
            sb.AppendLine($"    container_name: {name}");
            sb.AppendLine($"    hostname: {name}");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    entrypoint: /entrypoint.sh");
            sb.AppendLine("    env_file: .env");
            sb.AppendLine("    environment:");
            sb.AppendLine("      - CEPH_DAEMON=OSD_DIRECTORY");
            sb.AppendLine($"      - CEPH_PUBLIC_NETWORK={options.ClusterNetwork}");
            sb.AppendLine("    volumes:");
            sb.AppendLine($"      - {name}-data:/var/lib/ceph");
            sb.AppendLine("      - ceph-etc:/etc/ceph");
            sb.AppendLine("      - ./entrypoint.sh:/entrypoint.sh:ro");
            sb.AppendLine("    depends_on:");
            sb.AppendLine("      ceph-mon1:");
            sb.AppendLine("        condition: service_healthy");
            sb.AppendLine("    privileged: true");
            sb.AppendLine("    networks:");
            sb.AppendLine("      ceph-net:");
            sb.AppendLine($"        ipv4_address: {ip}");
            sb.AppendLine();
        }

        // Optional RGW
        if (options.IncludeRgw)
        {
            sb.AppendLine("  ceph-rgw:");
            sb.AppendLine($"    image: {options.CephImage}");
            sb.AppendLine("    container_name: ceph-rgw");
            sb.AppendLine("    hostname: ceph-rgw");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    entrypoint: /entrypoint.sh");
            sb.AppendLine("    env_file: .env");
            sb.AppendLine("    environment:");
            sb.AppendLine("      - CEPH_DAEMON=RGW");
            sb.AppendLine($"      - CEPH_PUBLIC_NETWORK={options.ClusterNetwork}");
            sb.AppendLine("    volumes:");
            sb.AppendLine("      - ceph-rgw-data:/var/lib/ceph");
            sb.AppendLine("      - ceph-etc:/etc/ceph");
            sb.AppendLine("      - ./entrypoint.sh:/entrypoint.sh:ro");
            sb.AppendLine("    ports:");
            sb.AppendLine("      - \"7480:7480\"");
            sb.AppendLine("    depends_on:");
            sb.AppendLine("      ceph-mon1:");
            sb.AppendLine("        condition: service_healthy");
            sb.AppendLine("    networks:");
            sb.AppendLine("      ceph-net:");
            sb.AppendLine("        ipv4_address: 172.20.4.1");
            sb.AppendLine();
        }

        // Optional MDS
        if (options.IncludeMds)
        {
            sb.AppendLine("  ceph-mds:");
            sb.AppendLine($"    image: {options.CephImage}");
            sb.AppendLine("    container_name: ceph-mds");
            sb.AppendLine("    hostname: ceph-mds");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    entrypoint: /entrypoint.sh");
            sb.AppendLine("    env_file: .env");
            sb.AppendLine("    environment:");
            sb.AppendLine("      - CEPH_DAEMON=MDS");
            sb.AppendLine($"      - CEPH_PUBLIC_NETWORK={options.ClusterNetwork}");
            sb.AppendLine("    volumes:");
            sb.AppendLine("      - ceph-mds-data:/var/lib/ceph");
            sb.AppendLine("      - ceph-etc:/etc/ceph");
            sb.AppendLine("      - ./entrypoint.sh:/entrypoint.sh:ro");
            sb.AppendLine("    depends_on:");
            sb.AppendLine("      ceph-mon1:");
            sb.AppendLine("        condition: service_healthy");
            sb.AppendLine("    networks:");
            sb.AppendLine("      ceph-net:");
            sb.AppendLine("        ipv4_address: 172.20.4.2");
            sb.AppendLine();
        }

        // Named volumes
        sb.AppendLine("volumes:");
        sb.AppendLine("  ceph-etc:");
        for (int i = 0; i < options.MonitorCount; i++)
            sb.AppendLine($"  ceph-mon{i + 1}-data:");
        for (int i = 0; i < options.MgrCount; i++)
            sb.AppendLine($"  ceph-mgr{i + 1}-data:");
        for (int i = 0; i < options.OsdCount; i++)
            sb.AppendLine($"  ceph-osd{i + 1}-data:");
        if (options.IncludeRgw)
            sb.AppendLine("  ceph-rgw-data:");
        if (options.IncludeMds)
            sb.AppendLine("  ceph-mds-data:");
        sb.AppendLine();

        // Network
        sb.AppendLine("networks:");
        sb.AppendLine("  ceph-net:");
        sb.AppendLine("    driver: bridge");
        sb.AppendLine("    ipam:");
        sb.AppendLine("      config:");
        sb.AppendLine($"        - subnet: {options.ClusterNetwork}");

        string path = Path.Combine(options.OutputDirectory, "docker-compose.yml");
        WriteUnixText(path, sb.ToString());
        return path;
    }

    // -------------------------------------------------------------------------
    // ceph.conf
    // -------------------------------------------------------------------------

    private string WriteCephConf(GenerateOptions options)
    {
        string monIps = string.Join(",", Enumerable.Range(1, options.MonitorCount).Select(i => $"172.20.1.{i}"));
        string monHosts = string.Join(",", Enumerable.Range(1, options.MonitorCount).Select(i => $"ceph-mon{i}"));

        string content = $"""
# Generated by ceph-cli
[global]
fsid = {Guid.NewGuid()}
mon_initial_members = {monHosts}
mon_host = {monIps}
auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx
osd_pool_default_size = {Math.Min(options.OsdCount, 3)}
osd_pool_default_min_size = 1
osd_journal_size = 1024

[osd]
osd_max_object_name_len = 256
osd_max_object_namespace_len = 64

""";

        string path = Path.Combine(options.OutputDirectory, "ceph.conf");
        WriteUnixText(path, content);
        return path;
    }

    // -------------------------------------------------------------------------
    // entrypoint.sh
    // -------------------------------------------------------------------------

    private string WriteEntrypointScript(GenerateOptions options)
    {
        string content = """
#!/bin/bash
# Generated by ceph-cli – container entrypoint for quay.io/ceph/ceph base image.
# This script bootstraps each Ceph daemon type from scratch.
set -e

if [ -z "${CEPH_DAEMON}" ]; then
  echo "ERROR: CEPH_DAEMON environment variable is not set."
  exit 1
fi

# Copy the seed ceph.conf into /etc/ceph if not already present.
# The MON bootstrap writes keyrings into /etc/ceph, so ceph.conf cannot
# be bind-mounted directly at /etc/ceph/ceph.conf (read-only mount would
# prevent keyring writes). Instead we stage it as /ceph.conf.seed and
# copy it here on first run.
if [ -f /ceph.conf.seed ] && [ ! -f /etc/ceph/ceph.conf ]; then
  cp /ceph.conf.seed /etc/ceph/ceph.conf
fi

CLUSTER="ceph"
MON_NAME=$(hostname -s)

case "${CEPH_DAEMON}" in
  MON)
    MON_DATA="/var/lib/ceph/mon/${CLUSTER}-${MON_NAME}"
    if [ ! -d "${MON_DATA}/store.db" ]; then
      echo "=== Bootstrapping MON ${MON_NAME} ==="

      # Create admin keyring
      if [ ! -f /etc/ceph/${CLUSTER}.client.admin.keyring ]; then
        ceph-authtool --create-keyring /etc/ceph/${CLUSTER}.client.admin.keyring \
          --gen-key -n client.admin \
          --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *'
      fi

      # Create mon keyring and import admin key
      ceph-authtool --create-keyring /tmp/${CLUSTER}.mon.keyring \
        --gen-key -n mon. --cap mon 'allow *'
      ceph-authtool /tmp/${CLUSTER}.mon.keyring \
        --import-keyring /etc/ceph/${CLUSTER}.client.admin.keyring

      # Create bootstrap keyrings
      mkdir -p /var/lib/ceph/bootstrap-osd /var/lib/ceph/bootstrap-mgr \
               /var/lib/ceph/bootstrap-mds /var/lib/ceph/bootstrap-rgw

      for svc in osd mgr mds rgw; do
        KR="/var/lib/ceph/bootstrap-${svc}/${CLUSTER}.keyring"
        if [ ! -f "${KR}" ]; then
          ceph-authtool --create-keyring "${KR}" \
            --gen-key -n "client.bootstrap-${svc}" --cap mon "profile bootstrap-${svc}"
          ceph-authtool /tmp/${CLUSTER}.mon.keyring --import-keyring "${KR}"
        fi
      done

      # Create monmap
      FSID=$(ceph-conf --lookup fsid)
      monmaptool --create --add "${MON_NAME}" "${MON_IP}:6789" --fsid "${FSID}" /tmp/monmap

      # Initialize MON
      mkdir -p "${MON_DATA}"
      ceph-mon --mkfs -i "${MON_NAME}" --monmap /tmp/monmap --keyring /tmp/${CLUSTER}.mon.keyring
      chown -R ceph:ceph /var/lib/ceph /etc/ceph
    fi

    echo "=== Starting MON ${MON_NAME} ==="
    exec ceph-mon -f --id "${MON_NAME}" --setuser ceph --setgroup ceph
    ;;

  MGR)
    echo "=== Waiting for MON to be ready ==="
    until ceph -s 2>/dev/null; do echo "  waiting for MON..."; sleep 5; done

    MGR_NAME=$(hostname -s)
    MGR_DATA="/var/lib/ceph/mgr/${CLUSTER}-${MGR_NAME}"
    if [ ! -d "${MGR_DATA}" ]; then
      echo "=== Bootstrapping MGR ${MGR_NAME} ==="
      mkdir -p "${MGR_DATA}"
      ceph auth get-or-create "mgr.${MGR_NAME}" \
        mon 'allow profile mgr' osd 'allow *' mds 'allow *' \
        > "${MGR_DATA}/keyring"
      chown -R ceph:ceph "${MGR_DATA}"
    fi

    echo "=== Starting MGR ${MGR_NAME} ==="
    exec ceph-mgr -f --id "${MGR_NAME}" --setuser ceph --setgroup ceph
    ;;

  OSD_DIRECTORY)
    echo "=== Waiting for MON to be ready ==="
    until ceph -s 2>/dev/null; do echo "  waiting for MON..."; sleep 5; done

    OSD_NAME=$(hostname -s)
    # Check if this OSD was already bootstrapped
    if [ ! -f /var/lib/ceph/.osd_id ]; then
      echo "=== Bootstrapping OSD on ${OSD_NAME} ==="
      OSD_UUID=$(python3 -c "import uuid; print(uuid.uuid4())")
      OSD_ID=$(ceph osd new "${OSD_UUID}")
      echo "${OSD_ID}" > /var/lib/ceph/.osd_id

      OSD_DATA="/var/lib/ceph/osd/${CLUSTER}-${OSD_ID}"
      mkdir -p "${OSD_DATA}"

      # Create a file-backed block device for bluestore (Ceph v18+ default).
      # Docker directory mounts do not provide real block devices, so we use
      # a sparse file and symlink it as the bluestore "block".
      BLOCK_FILE="/var/lib/ceph/osd-block-${OSD_ID}"
      dd if=/dev/zero of="${BLOCK_FILE}" bs=1M count=0 seek=5120 2>/dev/null
      ln -sf "${BLOCK_FILE}" "${OSD_DATA}/block"

      # Create the OSD keyring via the admin auth
      ceph auth get-or-create "osd.${OSD_ID}" \
        mon 'allow profile osd' osd 'allow *' mgr 'allow profile osd' \
        -o "${OSD_DATA}/keyring"

      # Prepare the OSD with bluestore
      ceph-osd -i "${OSD_ID}" --mkfs --osd-uuid "${OSD_UUID}" --no-mon-config

      ceph osd crush add "osd.${OSD_ID}" 1.0 host="${OSD_NAME}"
      chown -R ceph:ceph /var/lib/ceph
    fi

    OSD_ID=$(cat /var/lib/ceph/.osd_id)
    echo "=== Starting OSD ${OSD_ID} on ${OSD_NAME} ==="
    exec ceph-osd -f --id "${OSD_ID}" --setuser ceph --setgroup ceph
    ;;

  RGW)
    echo "=== Waiting for MON to be ready ==="
    until ceph -s 2>/dev/null; do echo "  waiting for MON..."; sleep 5; done

    RGW_NAME=$(hostname -s)
    RGW_DATA="/var/lib/ceph/radosgw/${CLUSTER}-rgw.${RGW_NAME}"
    if [ ! -d "${RGW_DATA}" ]; then
      echo "=== Bootstrapping RGW ${RGW_NAME} ==="
      mkdir -p "${RGW_DATA}"
      ceph auth get-or-create "client.rgw.${RGW_NAME}" \
        osd 'allow rwx' mon 'allow rw' \
        > "${RGW_DATA}/keyring"
      chown -R ceph:ceph "${RGW_DATA}"
    fi

    echo "=== Starting RGW ${RGW_NAME} ==="
    exec radosgw -f --name "client.rgw.${RGW_NAME}" --setuser ceph --setgroup ceph
    ;;

  MDS)
    echo "=== Waiting for MON to be ready ==="
    until ceph -s 2>/dev/null; do echo "  waiting for MON..."; sleep 5; done

    MDS_NAME=$(hostname -s)
    MDS_DATA="/var/lib/ceph/mds/${CLUSTER}-${MDS_NAME}"
    if [ ! -d "${MDS_DATA}" ]; then
      echo "=== Bootstrapping MDS ${MDS_NAME} ==="
      mkdir -p "${MDS_DATA}"
      ceph auth get-or-create "mds.${MDS_NAME}" \
        osd 'allow rwx' mds 'allow' mon 'allow profile mds' \
        > "${MDS_DATA}/keyring"
      chown -R ceph:ceph "${MDS_DATA}"
    fi

    echo "=== Starting MDS ${MDS_NAME} ==="
    exec ceph-mds -f --id "${MDS_NAME}" --setuser ceph --setgroup ceph
    ;;

  *)
    echo "ERROR: Unknown CEPH_DAEMON: ${CEPH_DAEMON}"
    echo "Valid values: MON, MGR, OSD_DIRECTORY, RGW, MDS"
    exit 1
    ;;
esac
""";

        string path = Path.Combine(options.OutputDirectory, "entrypoint.sh");
        WriteUnixText(path, content);
        return path;
    }

    // -------------------------------------------------------------------------
    // .env
    // -------------------------------------------------------------------------

    private string WriteEnvFile(GenerateOptions options)
    {
        string content = $"""
# Generated by ceph-cli – environment variables shared across all Ceph containers.
# Edit CEPH_DEMO_UID and CEPH_DEMO_ACCESS_KEY before using in production.
CEPH_DEMO_UID=ceph-demo
CEPH_DEMO_ACCESS_KEY=demo-access-key
CEPH_DEMO_SECRET_KEY=demo-secret-key
CEPH_DEMO_BUCKET=demo-bucket
NETWORK_AUTO_DETECT=4
""";

        string path = Path.Combine(options.OutputDirectory, ".env");
        WriteUnixText(path, content);
        return path;
    }

    // -------------------------------------------------------------------------
    // .wslconfig recommendation
    // -------------------------------------------------------------------------

    private string WriteWslConfig(GenerateOptions options)
    {
        string content = """
# Recommended WSL2 configuration for running Ceph in Docker Desktop on Windows.
# Copy this file to %USERPROFILE%\.wslconfig and restart WSL:  wsl --shutdown
[wsl2]
memory=6GB
swap=2GB
processors=4
localhostForwarding=true
""";

        string path = Path.Combine(options.OutputDirectory, "wslconfig.recommended");
        File.WriteAllText(path, content);
        return path;
    }

    // -------------------------------------------------------------------------
    // README.md
    // -------------------------------------------------------------------------

    private string WriteReadme(GenerateOptions options)
    {
        string content = """
# Ceph on Docker (Windows)

Generated by **ceph-cli**.

## Prerequisites

| Requirement | Minimum version |
|-------------|-----------------|
| Windows 10/11 | 21H2 or later |
| WSL2 | Default version 2 |
| Docker Desktop | 4.x |
| Docker Compose | v2 (bundled with Docker Desktop) |

## Quick Start

```powershell
# 1. Copy the recommended WSL2 configuration
Copy-Item wslconfig.recommended $env:USERPROFILE\.wslconfig
# Restart WSL
wsl --shutdown

# 2. Start the cluster
docker compose up -d

# 3. Check cluster health (wait ~30 s for bootstrap)
docker exec ceph-mon1 ceph health
docker exec ceph-mon1 ceph status
```

## Files

| File | Purpose |
|------|---------|
| `docker-compose.yml` | Defines all Ceph services |
| `ceph.conf` | Ceph cluster configuration |
| `entrypoint.sh` | Container start helper |
| `.env` | Shared environment variables |
| `wslconfig.recommended` | Recommended `~/.wslconfig` settings |

## Troubleshooting

Run the CLI diagnostic tool at any time:

```powershell
ceph-cli diagnose
ceph-cli fix
```

## Common Issues on Windows

### Containers crash immediately
Ensure WSL2 is set as the default: `wsl --set-default-version 2`

### Docker daemon not reachable
Start Docker Desktop and wait for it to be fully running.

### Out of memory / OOM killer
Increase WSL2 memory in `~/.wslconfig` (`memory=8GB`) and run `wsl --shutdown`.

### Volume permission errors
OSD containers require `privileged: true` (already set in the generated Compose file).
""";

        string path = Path.Combine(options.OutputDirectory, "README.md");
        File.WriteAllText(path, content);
        return path;
    }
}
