namespace Ceph.Cli.Services;

/// <summary>
/// Generates docker-compose files and supporting configuration to run a Ceph
/// cluster inside Docker on Windows (via WSL2 / Docker Desktop).
/// </summary>
public class DockerComposeGenerator
{
    public record GenerateOptions(
        string OutputDirectory,
        int MonitorCount = 1,
        int OsdCount = 3,
        int MgrCount = 1,
        string CephImage = "quay.io/ceph/ceph:v18",
        string ClusterNetwork = "172.20.0.0/16",
        bool IncludeRgw = false,
        bool IncludeMds = false
    );

    /// <summary>Generates all files into <paramref name="options"/>.OutputDirectory.</summary>
    public IReadOnlyList<string> Generate(GenerateOptions options)
    {
        Directory.CreateDirectory(options.OutputDirectory);
        var files = new List<string>();

        files.Add(WriteDockerCompose(options));
        files.Add(WriteCephConf(options));
        files.Add(WriteEntrypointScript(options));
        files.Add(WriteEnvFile(options));
        files.Add(WriteReadme(options));
        files.Add(WriteWslConfig(options));

        return files;
    }

    // -------------------------------------------------------------------------
    // docker-compose.yml
    // -------------------------------------------------------------------------

    private string WriteDockerCompose(GenerateOptions options)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Generated by ceph-cli – do not edit manually unless you know what you are doing.");
        sb.AppendLine("# Run with: docker compose up -d");
        sb.AppendLine();
        sb.AppendLine("services:");

        // MON services
        for (int i = 0; i < options.MonitorCount; i++)
        {
            string name = $"ceph-mon{i + 1}";
            string ip = $"172.20.1.{i + 1}";
            sb.AppendLine($"  {name}:");
            sb.AppendLine($"    image: {options.CephImage}");
            sb.AppendLine($"    container_name: {name}");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    env_file: .env");
            sb.AppendLine("    environment:");
            sb.AppendLine($"      - MON_IP={ip}");
            sb.AppendLine("      - CEPH_DAEMON=MON");
            sb.AppendLine("    volumes:");
            sb.AppendLine($"      - {name}-data:/var/lib/ceph");
            sb.AppendLine("      - ./ceph.conf:/etc/ceph/ceph.conf:ro");
            sb.AppendLine("      - ./entrypoint.sh:/entrypoint.sh:ro");
            sb.AppendLine("    networks:");
            sb.AppendLine("      ceph-net:");
            sb.AppendLine($"        ipv4_address: {ip}");
            sb.AppendLine("    healthcheck:");
            sb.AppendLine("      test: [\"CMD\", \"ceph\", \"health\"]");
            sb.AppendLine("      interval: 30s");
            sb.AppendLine("      timeout: 10s");
            sb.AppendLine("      retries: 5");
            sb.AppendLine();
        }

        // MGR services
        for (int i = 0; i < options.MgrCount; i++)
        {
            string name = $"ceph-mgr{i + 1}";
            string ip = $"172.20.2.{i + 1}";
            sb.AppendLine($"  {name}:");
            sb.AppendLine($"    image: {options.CephImage}");
            sb.AppendLine($"    container_name: {name}");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    env_file: .env");
            sb.AppendLine("    environment:");
            sb.AppendLine("      - CEPH_DAEMON=MGR");
            sb.AppendLine("    volumes:");
            sb.AppendLine($"      - {name}-data:/var/lib/ceph");
            sb.AppendLine("      - ./ceph.conf:/etc/ceph/ceph.conf:ro");
            sb.AppendLine("    depends_on:");
            sb.AppendLine("      - ceph-mon1");
            sb.AppendLine("    networks:");
            sb.AppendLine("      ceph-net:");
            sb.AppendLine($"        ipv4_address: {ip}");
            sb.AppendLine();
        }

        // OSD services
        for (int i = 0; i < options.OsdCount; i++)
        {
            string name = $"ceph-osd{i + 1}";
            string ip = $"172.20.3.{i + 1}";
            sb.AppendLine($"  {name}:");
            sb.AppendLine($"    image: {options.CephImage}");
            sb.AppendLine($"    container_name: {name}");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    env_file: .env");
            sb.AppendLine("    environment:");
            sb.AppendLine("      - CEPH_DAEMON=OSD_DIRECTORY");
            sb.AppendLine("    volumes:");
            sb.AppendLine($"      - {name}-data:/var/lib/ceph/osd");
            sb.AppendLine("      - ./ceph.conf:/etc/ceph/ceph.conf:ro");
            sb.AppendLine("    depends_on:");
            sb.AppendLine("      - ceph-mon1");
            sb.AppendLine("      - ceph-mgr1");
            sb.AppendLine("    privileged: true");
            sb.AppendLine("    networks:");
            sb.AppendLine("      ceph-net:");
            sb.AppendLine($"        ipv4_address: {ip}");
            sb.AppendLine();
        }

        // Optional RGW
        if (options.IncludeRgw)
        {
            sb.AppendLine("  ceph-rgw:");
            sb.AppendLine($"    image: {options.CephImage}");
            sb.AppendLine("    container_name: ceph-rgw");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    env_file: .env");
            sb.AppendLine("    environment:");
            sb.AppendLine("      - CEPH_DAEMON=RGW");
            sb.AppendLine("    volumes:");
            sb.AppendLine("      - ceph-rgw-data:/var/lib/ceph");
            sb.AppendLine("      - ./ceph.conf:/etc/ceph/ceph.conf:ro");
            sb.AppendLine("    ports:");
            sb.AppendLine("      - \"7480:7480\"");
            sb.AppendLine("    depends_on:");
            sb.AppendLine("      - ceph-mon1");
            sb.AppendLine("    networks:");
            sb.AppendLine("      ceph-net:");
            sb.AppendLine("        ipv4_address: 172.20.4.1");
            sb.AppendLine();
        }

        // Optional MDS
        if (options.IncludeMds)
        {
            sb.AppendLine("  ceph-mds:");
            sb.AppendLine($"    image: {options.CephImage}");
            sb.AppendLine("    container_name: ceph-mds");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    env_file: .env");
            sb.AppendLine("    environment:");
            sb.AppendLine("      - CEPH_DAEMON=MDS");
            sb.AppendLine("    volumes:");
            sb.AppendLine("      - ceph-mds-data:/var/lib/ceph");
            sb.AppendLine("      - ./ceph.conf:/etc/ceph/ceph.conf:ro");
            sb.AppendLine("    depends_on:");
            sb.AppendLine("      - ceph-mon1");
            sb.AppendLine("    networks:");
            sb.AppendLine("      ceph-net:");
            sb.AppendLine("        ipv4_address: 172.20.4.2");
            sb.AppendLine();
        }

        // Named volumes
        sb.AppendLine("volumes:");
        for (int i = 0; i < options.MonitorCount; i++)
            sb.AppendLine($"  ceph-mon{i + 1}-data:");
        for (int i = 0; i < options.MgrCount; i++)
            sb.AppendLine($"  ceph-mgr{i + 1}-data:");
        for (int i = 0; i < options.OsdCount; i++)
            sb.AppendLine($"  ceph-osd{i + 1}-data:");
        if (options.IncludeRgw)
            sb.AppendLine("  ceph-rgw-data:");
        if (options.IncludeMds)
            sb.AppendLine("  ceph-mds-data:");
        sb.AppendLine();

        // Network
        sb.AppendLine("networks:");
        sb.AppendLine("  ceph-net:");
        sb.AppendLine("    driver: bridge");
        sb.AppendLine("    ipam:");
        sb.AppendLine("      config:");
        sb.AppendLine($"        - subnet: {options.ClusterNetwork}");

        string path = Path.Combine(options.OutputDirectory, "docker-compose.yml");
        File.WriteAllText(path, sb.ToString());
        return path;
    }

    // -------------------------------------------------------------------------
    // ceph.conf
    // -------------------------------------------------------------------------

    private string WriteCephConf(GenerateOptions options)
    {
        string monIps = string.Join(",", Enumerable.Range(1, options.MonitorCount).Select(i => $"172.20.1.{i}"));
        string monHosts = string.Join(",", Enumerable.Range(1, options.MonitorCount).Select(i => $"ceph-mon{i}"));

        string content = $"""
# Generated by ceph-cli
[global]
fsid = {Guid.NewGuid()}
mon_initial_members = {monHosts}
mon_host = {monIps}
auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx
osd_pool_default_size = {Math.Min(options.OsdCount, 3)}
osd_pool_default_min_size = 1
osd_journal_size = 1024

[osd]
osd_max_object_name_len = 256
osd_max_object_namespace_len = 64
""";

        string path = Path.Combine(options.OutputDirectory, "ceph.conf");
        File.WriteAllText(path, content);
        return path;
    }

    // -------------------------------------------------------------------------
    // entrypoint.sh
    // -------------------------------------------------------------------------

    private string WriteEntrypointScript(GenerateOptions options)
    {
        string content = """
#!/bin/bash
# Generated by ceph-cli – container entrypoint helper
set -e

if [ -z "${CEPH_DAEMON}" ]; then
  echo "ERROR: CEPH_DAEMON environment variable is not set."
  exit 1
fi

exec /opt/ceph-container/bin/entrypoint.sh
""";

        string path = Path.Combine(options.OutputDirectory, "entrypoint.sh");
        File.WriteAllText(path, content);
        return path;
    }

    // -------------------------------------------------------------------------
    // .env
    // -------------------------------------------------------------------------

    private string WriteEnvFile(GenerateOptions options)
    {
        string content = $"""
# Generated by ceph-cli – environment variables shared across all Ceph containers.
# Edit CEPH_DEMO_UID and CEPH_DEMO_ACCESS_KEY before using in production.
CEPH_DEMO_UID=ceph-demo
CEPH_DEMO_ACCESS_KEY=demo-access-key
CEPH_DEMO_SECRET_KEY=demo-secret-key
CEPH_DEMO_BUCKET=demo-bucket
NETWORK_AUTO_DETECT=4
""";

        string path = Path.Combine(options.OutputDirectory, ".env");
        File.WriteAllText(path, content);
        return path;
    }

    // -------------------------------------------------------------------------
    // .wslconfig recommendation
    // -------------------------------------------------------------------------

    private string WriteWslConfig(GenerateOptions options)
    {
        string content = """
# Recommended WSL2 configuration for running Ceph in Docker Desktop on Windows.
# Copy this file to %USERPROFILE%\.wslconfig and restart WSL:  wsl --shutdown
[wsl2]
memory=6GB
swap=2GB
processors=4
localhostForwarding=true
""";

        string path = Path.Combine(options.OutputDirectory, "wslconfig.recommended");
        File.WriteAllText(path, content);
        return path;
    }

    // -------------------------------------------------------------------------
    // README.md
    // -------------------------------------------------------------------------

    private string WriteReadme(GenerateOptions options)
    {
        string content = """
# Ceph on Docker (Windows)

Generated by **ceph-cli**.

## Prerequisites

| Requirement | Minimum version |
|-------------|-----------------|
| Windows 10/11 | 21H2 or later |
| WSL2 | Default version 2 |
| Docker Desktop | 4.x |
| Docker Compose | v2 (bundled with Docker Desktop) |

## Quick Start

```powershell
# 1. Copy the recommended WSL2 configuration
Copy-Item wslconfig.recommended $env:USERPROFILE\.wslconfig
# Restart WSL
wsl --shutdown

# 2. Start the cluster
docker compose up -d

# 3. Check cluster health (wait ~30 s for bootstrap)
docker exec ceph-mon1 ceph health
docker exec ceph-mon1 ceph status
```

## Files

| File | Purpose |
|------|---------|
| `docker-compose.yml` | Defines all Ceph services |
| `ceph.conf` | Ceph cluster configuration |
| `entrypoint.sh` | Container start helper |
| `.env` | Shared environment variables |
| `wslconfig.recommended` | Recommended `~/.wslconfig` settings |

## Troubleshooting

Run the CLI diagnostic tool at any time:

```powershell
ceph-cli diagnose
ceph-cli fix
```

## Common Issues on Windows

### Containers crash immediately
Ensure WSL2 is set as the default: `wsl --set-default-version 2`

### Docker daemon not reachable
Start Docker Desktop and wait for it to be fully running.

### Out of memory / OOM killer
Increase WSL2 memory in `~/.wslconfig` (`memory=8GB`) and run `wsl --shutdown`.

### Volume permission errors
OSD containers require `privileged: true` (already set in the generated Compose file).
""";

        string path = Path.Combine(options.OutputDirectory, "README.md");
        File.WriteAllText(path, content);
        return path;
    }
}
